name: Issue Assigner

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: pozil/auto-assign-issue@v2.1.2
        with:
          assignees: HiromiShikata
          repo-token: ${{ secrets.GH_TOKEN }}
